# Generated by Django 5.2.9 on 2026-01-05 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CameraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mount', models.CharField(blank=True, max_length=50, null=True)),
                ('sensor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_models', to='market.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('avito', 'Avito'), ('youla', 'Youla'), ('other', 'Other')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(default='RUB', max_length=10)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('parts', 'For parts')], default='used', max_length=20)),
                ('region', models.CharField(max_length=120)),
                ('seller_type', models.CharField(blank=True, max_length=50, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('camera_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='market.cameramodel')),
            ],
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('currency', models.CharField(default='RUB', max_length=10)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='market.listing')),
            ],
        ),
        migrations.CreateModel(
            name='WatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.IntegerField()),
                ('preferred_condition', models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('parts', 'For parts')], max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('camera_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.cameramodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
