# Generated by Django 5.2.9 on 2026-01-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='posted_at',
        ),
        migrations.AddField(
            model_name='listing',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
