# Generated by Django 5.2.9 on 2026-01-06 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_listing_posted_at_listing_posted_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchitem',
            name='camera_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_items', to='market.cameramodel'),
        ),
        migrations.AlterField(
            model_name='watchitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='watchitem',
            constraint=models.UniqueConstraint(fields=('user', 'camera_model'), name='uniq_watchitem_user_camera_model'),
        ),
    ]
