# Generated by Django 5.2.9 on 2026-01-07 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_watchitem_camera_model_alter_watchitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramodel',
            name='avito_search_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='camera_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.cameramodel'),
        ),
    ]
