# Generated by Django 5.2.9 on 2026-01-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_cameramodel_avito_search_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
