# Generated by Django 5.2.9 on 2026-01-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_listing_is_active_listing_last_seen_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_listing_source_external_id'),
        ),
    ]
