# Generated by Django 5.2.9 on 2026-01-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_listing_uniq_listing_source_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='external_id',
            field=models.CharField(max_length=100),
        ),
    ]
