# Generated by Django 5.2.9 on 2026-01-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_listing_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='watchitem',
            name='preferred_condition',
        ),
        migrations.AlterField(
            model_name='listing',
            name='source',
            field=models.CharField(choices=[('avito', 'Avito')], max_length=20),
        ),
    ]
