# Generated by Django 5.2.9 on 2026-01-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_remove_condition_and_other_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramodel',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Ссылка на изображение камеры'),
        ),
    ]
